name: Pull Request Metadata

on:
  pull_request:
    types:
      - opened
#    branches:
#      - '*'

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: |
            "waiting CI check"
            "under verification"
            "waiting peer review"
  add_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add Pull Request Reviewer
        uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
        with:
          reviewers: baranowb,ropalka,frainone,jamezp,jasondlee
          token: ${{ secrets.GITHUB_TOKEN }}
