name: Pull Request Metadata

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened]
#    branches:
#      - '*'

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            waiting CI check
            under verification
            waiting peer review
  
  add_reviewers1:
    runs-on: ubuntu-latest
    steps:
      - name: Vet reviewer list
        id: reviewers
        run: |
          #this needs to be done since github wont allow author to be assigned
          reviewers_init='"baranowb frainone jamezp jasondlee ropalka"'
          reviewers=''
          for rev in $variable
          do
            if [ "$rev" != "${{ github.event.pull_request.user.login }}" ]; then
              echo "adding '$rev' to reviewer list."
              if [[-z "$myVar"]]; then
                reviewers="$rev"
              else
                reviewers="$reviewers, $rev"
              fi
            else
              echo "Ignoring '$rev' as he is author"
            fi
          done

          echo "Reviewers: '$reviewers'"
          echo "REVIEWERS=$reviewers" >> "$GITHUB_ENV"
          # https://github.com/marketplace/actions/get-current-pom-version-of-project ?
      - name: Add Pull Request Reviewer
        uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
        with:
          reviewers: "$REVIEWERS"
          token: ${{ secrets.GITHUB_TOKEN }}
